const POSTS = [
  {
    id: 1,
    img_url: "https://random.imagecdn.app/300/300",
    title: "Interesting Find",
    username: "adventurous_soul",
    description: "Stumbled upon #test_test something amazing today! #test",
    likes: 25,
  },
  {
    id: 2,
    img_url: "https://random.imagecdn.app/300/301",
    title: "Nature's Beauty",
    username: "wanderlust_lover",
    description: "Caught this breathtaking #test_hash view during my hike!",
    likes: 18,
  },
  {
    id: 3,
    img_url: "https://random.imagecdn.app/301/300",
    title: "Favorite Recipe",
    username: "culinary_expert",
    description: "Cooked up a storm #test_hash2 in the kitchen today!",
    likes: 12,
  },
  {
    id: 4,
    img_url: "https://random.imagecdn.app/1200/300",
    title: "New Adventure Awaits",
    username: "explorer_mind",
    description: "Planning my next thrilling expedition!",
    likes: 30,
  },
  {
    id: 5,
    img_url: "https://random.imagecdn.app/500/500",
    title: "Artistic Inspiration",
    username: "creative_visionary",
    description: "Found inspiration in the most unexpected place!",
    likes: 15,
  },
  {
    id: 6,
    img_url: "https://random.imagecdn.app/300/1200",
    title: "Memories of the Past",
    username: "nostalgia_seeker",
    description: "Reflecting on some cherished moments today.",
    likes: 8,
  },
  {
    id: 7,
    img_url: "https://random.imagecdn.app/399/305",
    title: "Fitness Journey",
    username: "health_fanatic",
    description: "Making progress on my fitness goals!",
    likes: 20,
  },
  {
    id: 8,
    img_url: "https://random.imagecdn.app/500/550",
    title: "Tech Discoveries",
    username: "digital_nomad",
    description: "Exciting tech finds from my travels!",
    likes: 14,
  },
  {
    id: 9,
    img_url: "https://random.imagecdn.app/500/510",
    title: "Thoughts on Philosophy",
    username: "philosophy_buff",
    description: "Contemplating the deeper questions of life.",
    likes: 22,
  },
  {
    id: 10,
    img_url: "https://random.imagecdn.app/311/300",
    title: "Fashion Frenzy",
    username: "trendy_style",
    description: "Experimenting with some bold fashion choices!",
    likes: 17,
  },
  {
    id: 11,
    img_url: "https://random.imagecdn.app/300/311",
    title: "Musical Exploration",
    username: "melody_seeker",
    description: "Diving into a diverse range of musical genres.",
    likes: 19,
  },
  {
    id: 12,
    img_url: "https://random.imagecdn.app/400/300",
    title: "Travel Chronicles",
    username: "globetrotter_life",
    description: "Uncovering hidden gems on my latest journey!",
    likes: 24,
  },
  {
    id: 13,
    img_url: "https://random.imagecdn.app/1920/1080",
    title: "Mindful Meditation",
    username: "inner_peace_seeker",
    description: "Finding serenity through daily meditation practices.",
    likes: 11,
  },

  {
    id: 14,
    img_url: "https://random.imagecdn.app/1080/1920",
    title: "Literary Adventures",
    username: "bookworm_reader",
    description: "Exploring new worlds through the pages of a book!",
    likes: 16,
  },
  {
    id: 15,
    img_url: "https://random.imagecdn.app/1080/1000",
    title: "Culinary Delights",
    username: "foodie_adventures",
    description: "Indulging in some delightful culinary experiences!",
    likes: 21,
  },
  {
    id: 16,
    img_url: "https://random.imagecdn.app/435/435",
    title: "Travel Memories",
    username: "wanderlust_soul",
    description: "Reminiscing about past adventures on the road!",
    likes: 27,
  },
  {
    id: 17,
    img_url: "https://random.imagecdn.app/234/432",
    title: "Exploring the City",
    username: "urban_explorer",
    description: "Discovering hidden gems in the heart of the city.",
    likes: 13,
  },
  {
    id: 18,
    img_url: "https://random.imagecdn.app/353/412",
    title: "Fitness Goals Achieved",
    username: "fitness_junkie",
    description: "Celebrating reaching my fitness milestones!",
    likes: 29,
  },
  {
    id: 19,
    img_url: "https://random.imagecdn.app/332/412",
    title: "Artistic Creations",
    username: "creative_mindset",
    description: "Channeling creativity into stunning art pieces.",
    likes: 26,
  },
  {
    id: 20,
    img_url: "https://random.imagecdn.app/353/424",
    title: "Morning Reflections",
    username: "early_riser",
    description: "Starting the day with mindful thoughts and gratitude.",
    likes: 23,
  },
  {
    id: 21,
    img_url: "https://random.imagecdn.app/310/401",
    title: "Coding Adventures",
    username: "tech_enthusiast",
    description: "Cracking complex codes and building innovative projects!",
    likes: 28,
  },
  {
    id: 22,
    img_url: "https://random.imagecdn.app/410/401",
    title: "Mountain Escapades",
    username: "peak_adventurer",
    description: "Conquering new heights with every climb!",
    likes: 31,
  },
  {
    id: 23,
    img_url: "https://random.imagecdn.app/200/201",
    title: "Philosophical Musings",
    username: "deep_thinker",
    description: "Contemplating the mysteries of existence.",
    likes: 16,
  },
  {
    id: 24,
    img_url: "https://random.imagecdn.app/500/301",
    title: "Stylish Moments",
    username: "fashionista_life",
    description: "Elevating everyday looks with a touch of style!",
    likes: 19,
  },
];

export default POSTS;
